[package]
name = "egomoose/viewport-window"
authors = ["EgoMoose", "EmilyBendsSpace"]
description = "https://github.com/EgoMoose/rbx-viewport-window"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]

[dependencies]
Trove = "sleitnick/trove@1.5.0"